# Generated by Django 6.0.4 on 2026-05-20 23:32

from django.db import migrations

def set_superuser_role_owner(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(is_superuser=True).update(role='OWNER')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RunPython(set_superuser_role_owner, reverse_code=migrations.RunPython.noop),
    ]