# Generated by Django 6.0.4 on 2026-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_set_superuser_role_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
