# Generated by Django 6.0.4 on 2026-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='skip_auto_reactivation',
            field=models.BooleanField(default=False),
        ),
    ]
