# Generated by Django 4.2 on 2026-03-30 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('SALE_VOID', 'Sale Void'), ('PRICE_CHANGE', 'Price Change'), ('STOCK_ADJUST', 'Stock Adjust'), ('CREDIT_PAY', 'Credit Payment'), ('SALE_CREATE', 'Sale Create'), ('PRODUCT_CREATE', 'Product Create'), ('PRODUCT_UPDATE', 'Product Update')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
