# Generated by Django 4.2 on 2026-04-17 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='http_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATE', 'Sale Created'), ('SALE_VOID', 'Sale Voided'), ('PRICE_CHANGE', 'Price Changed'), ('STOCK_ADJUST', 'Stock Adjusted'), ('CREDIT_PAYMENT', 'Credit Payment'), ('PRODUCT_CREATE', 'Product Created'), ('PRODUCT_UPDATE', 'Product Updated'), ('PRODUCT_DELETE', 'Product Deleted'), ('CUSTOMER_CREATE', 'Customer Created'), ('CUSTOMER_UPDATE', 'Customer Updated'), ('CUSTOMER_DELETE', 'Customer Deleted'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('BACKUP_DOWNLOAD', 'Backup Downloaded'), ('BACKUP_RESTORE', 'Backup Restored'), ('INVITE_CASHIER', 'Cashier Invited')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, help_text='Additional context (e.g., old value, new value, reason)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['shop', '-created_at'], name='audit_audit_shop_id_be352b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_audit_action_86e815_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'),
        ),
    ]
