# Generated by Django 6.0.4 on 2026-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_options_auditlog_http_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='summary',
            field=models.TextField(blank=True, help_text='Human-readable description of the action'),
        ),
    ]
