# Generated by Django 6.0.4 on 2026-05-12 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_summary'),
        ('users', '0004_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATE', 'Sale Created'), ('SALE_VOID', 'Sale Voided'), ('PRICE_CHANGE', 'Price Changed'), ('STOCK_ADJUST', 'Stock Adjusted'), ('CREDIT_PAYMENT', 'Credit Payment'), ('PRODUCT_CREATE', 'Product Created'), ('PRODUCT_UPDATE', 'Product Updated'), ('PRODUCT_DELETE', 'Product Deleted'), ('CUSTOMER_CREATE', 'Customer Created'), ('CUSTOMER_UPDATE', 'Customer Updated'), ('CUSTOMER_DELETE', 'Customer Deleted'), ('LOGIN', 'User Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'User Logout'), ('BACKUP_DOWNLOAD', 'Backup Downloaded'), ('BACKUP_RESTORE', 'Backup Restored'), ('INVITE_CASHIER', 'Cashier Invited')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'),
        ),
    ]
