# Generated by Django 6.0.4 on 2026-05-23 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditlog_shop'),
        ('users', '0005_set_superuser_role_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['shop', 'action', 'created_at'], name='audit_audit_shop_id_798013_idx'),
        ),
    ]
