# Generated by Django 6.0.4 on 2026-05-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
