# Generated by Django 6.0.4 on 2026-04-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_credittransaction_idempotency_key'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credittransaction', to='sales.sale'),
        ),
    ]
