# Generated by Django 6.0.4 on 2026-05-12 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_credittransaction_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
