# Generated by Django 6.0.4 on 2026-06-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
