# Generated by Django 6.0.4 on 2026-07-03 10:25

from django.db import migrations

def set_initial_stock(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    # Get all products that lack initial_stock
    products_to_fix = Product.objects.filter(
        custom_fields__initial_stock__isnull=True
    )
    for product in products_to_fix:
        # Set it to the current stock value
        product.custom_fields['initial_stock'] = product.current_stock
        product.save(update_fields=['custom_fields'])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_custom_fields'),
    ]

    operations = [
        migrations.RunPython(
            set_initial_stock,
            reverse_code=migrations.RunPython.noop
        ),
    ]
