# Generated by Django 6.0.4 on 2026-05-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='momo_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
