# Generated by Django 6.0.4 on 2026-05-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_momo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
