# Generated by Django 6.0.4 on 2026-05-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
