# Generated by Django 6.0.4 on 2026-05-23 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_credittransaction_customer_and_more'),
        ('products', '0002_initial'),
        ('sales', '0005_alter_sale_idempotency_key'),
        ('users', '0005_set_superuser_role_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop', 'created_at'], name='sales_sale_shop_id_a0d636_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop', 'status'], name='sales_sale_shop_id_bfcf48_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='sales_sale_custome_f0dcab_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='sales_salei_sale_id_413ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='sales_salei_product_f87493_idx'),
        ),
    ]
