# Generated by Django 6.0.4 on 2026-06-22 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_credittransaction_customer_and_more'),
        ('sales', '0006_sale_sales_sale_shop_id_a0d636_idx_and_more'),
        ('users', '0007_shop_skip_auto_reactivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_backdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='original_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_backdated'], name='sales_sale_is_back_2ab0aa_idx'),
        ),
    ]
